[package]
name = "zinit"
version = "0.1.0"
authors = ["Muhamad Azmy <muhamad.azmy@codescalers.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.8"
futures = "0.1"
tokio = "0.1"
tokio-process = "0.2"
tokio-serde-json = "0.2.0"
failure = "0.1"
shlex = "0.1"
clap = "2.33"
